# Generated by Django 5.2.8 on 2025-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, editable=False, null=True)),
                ('anotacoes', models.TextField(blank=True, help_text='Campo exclusivo para o profissional (Prontuário)', null=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não Compareceu')], default='AGENDADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(default='09:00')),
                ('hora_fim', models.TimeField(default='18:00')),
                ('almoco_inicio', models.TimeField(blank=True, default='12:00', null=True)),
                ('almoco_fim', models.TimeField(blank=True, default='13:00', null=True)),
                ('folga', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='portfolio/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao_minutos', models.PositiveIntegerField(help_text='Duração em minutos')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
