# Generated by Django 5.2.8 on 2025-11-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='anotacoes',
            field=models.TextField(blank=True, help_text='Campo exclusivo para o profissional (Prontuário)', null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
