# Generated by Django 5.2.8 on 2025-11-29 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_anotacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(default='09:00')),
                ('hora_fim', models.TimeField(default='18:00')),
                ('almoco_inicio', models.TimeField(blank=True, default='12:00', null=True)),
                ('almoco_fim', models.TimeField(blank=True, default='13:00', null=True)),
                ('folga', models.BooleanField(default=False)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('profissional', 'dia_semana')},
            },
        ),
    ]
